config/routes.rb
Rails.application.routes.draw do
   devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  root to: "public/homes#top"
   scope module: :public do
    patch "customers/withdrawal" => "customers#withdrawal"
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    get "public/items" => "items#index"
    resources :items, only: [:show]
    get "/about" => "homes#about"
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    get "customers/check" => "customers#check"
    resources :customers, only: [:new, :create, :destroy, :update]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]

   end

   namespace :admin do
    resources :customers, only: [:show, :edit, :update]
    get "customers" => "customers#index"
    resources :items, only: [:new, :create, :show, :edit, :update]
    get "/" => "homes#top"
    get "items" => "items#index"
    resources :orders, only: [:show]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_items

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default_image.jpg',  content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="containar d-flex justify-content-center">
<%= form_with model: @item, url:admin_item_path(@item.id), method: :patch do |f| %>
<h1>商品編集</h1>
  <p>商品画像 <%= f.file_field :image, accept: "image/*" %></p>
  <p>商品名 <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control" %></p>
  <p>商品説明 <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class:"form-control" %></p>
  <p>税抜価格 <%= f.text_field :price, autofocus: true, id:"inputPrice", class:"form-control" %></p>
  <%= f.submit "変更を保存", class:"btn btn-success" %>
<% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container justify-content-center">
  <h1>商品一覧 <%= link_to "新規登録", new_admin_item_path, class:"btn btn-primary" %></h1>
    <table class="table table-hover table-inverse mt-5">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜き価格</th>
        </tr>
      </thead>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %>円</td>
      </tr>
      <% end %>
    </table>
</div>

app/views/admin/items/new.html.erb
<div class="containar d-flex justify-content-center">
  <%= form_with model: @item, url:admin_items_path do |f| %>
  <h1>商品新規登録</h1>
    <h4>商品画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
    <h4>商品名</h4>
    <%= f.text_field :name, class:"form-control" %>
    <h4>商品説明</h4>
    <%= f.text_area :introduction, class:"form-control" %>
    <h4>税抜価格</h4>
    <%= f.text_field :price, class:"form-control" %><p>円</p>
    <%= f.submit '新規登録',class:"btn btn-success" %>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container justify-content-center">
<h1>商品詳細</h1>
  <div class="row">
    <div class="col-md-4 p-5">
     <%= image_tag @item.get_image(300,300) %>
    </div>
    <div class="col-md-8 p-5">
      <p>商品名:<%= @item.name %></p>
      <p>商品説明<%= @item.introduction %></p>
      <p>税込価格(税抜価格)<%=rounded_price(@item.price*1.1) %> (<%= @item.price %>)円</p>

      <%= link_to "編集する", edit_admin_item_path, class:"btn btn-success" %>
    </div>
  </div>
</div>