config/routes.rb
Rails.application.routes.draw do
   devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  root to: "public/homes#top"
   scope module: :public do
    patch "customers/withdrawal" => "customers#withdrawal"
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    get "public/items" => "items#index"
    resources :items, only: [:show]
    get "/about" => "homes#about"
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    get "customers/check" => "customers#check"
    resources :customers, only: [:new, :create, :destroy, :update]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]

   end

   namespace :admin do
    resources :customers, only: [:show, :edit, :update]
    get "customers" => "customers#index"
    resources :items, only: [:new, :create, :show, :edit, :update]
    get "/" => "homes#top"
    get "items" => "items#index"
    resources :orders, only: [:show]
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :cart_items
has_many :orders

def full_name
  self.last_name+self.first_name
end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="containar d-flex justify-content-start p-5">
<%= form_with model: @customer, url: admin_customer_path do |f| %>
<strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</strong>
  <p>会員ID <%= @customer.id %></p>
  <div class="input-group m-3">
    氏名  <%= f.text_field :last_name, autofocus: true, id:"inputLastName", class:"form-control" %>
          <%= f.text_field :first_name, autofocus: true, id:"inputFirstName", class:"form-control"  %>
  </div>
  <div class="input-group m-3">
    フリガナ  <%= f.text_field :last_name_kana, autofocus: true, id:"inputLastNameKana", class:"form-control" %>
                <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirstNameKana", class:"form-control" %>
  </div>
  <p>郵便番号 <%= f.text_field :postal_code, autofocus: true, id:"inputPostalCode", class:"form-control" %></p>
  <p>住所 <%= f.text_field :address, autofocus: true, id:"inputAdress", class:"form-control" %></p>
  <p>電話番号 <%= f.text_field :telephone_number, autofocus: true, id:"inputTelephoneNumber", class:"form-control" %></p>
  <p>メールアドレス <%= f.text_field :email, autofocus: true, id:"inputEmail", class:"form-control" %></p>
  <p>会員ステータス
  <div><%= f.radio_button :is_active, true, cheched:@customer.is_active == true, id: 'status-active' %>
       <%= f.label :is_active, '有効', for: 'status-active' %></div>
  <div><%= f.radio_button :is_active, false, cheched:@customer.is_active == false, id: 'status-deleted' %>
       <%= f.label :is_active, '退会済み', for: 'status-deleted' %></div>
  </p>

  <%= f.submit "変更を保存", class:"btn btn-success" %>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container justify-content-center">
  <h1>会員一覧</h1>
    <table class="table table-hover table-inverse mt-5">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
     <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to admin_customer_path(customer.id) do %>
          <%= customer.last_name %><%= customer.first_name %>
          <% end %></td>
        <td><%= customer.email %></td>
        <% if customer.is_active %>
          <td><p class="text-success">有効</p></td>
         <% elsif %>
          <td><p class="text-meted">退会</p></td>
        <% end %>
      </tr>
     <% end %>
    </table>
    <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="containar justify-content-center m-5">
    <strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</strong>

    <p>会員ID <%= @customer.id %></p>
    <p>氏名 <%= @customer.last_name %> <%= @customer.first_name %></p>
    <p>フリガナ <%= @customer.last_name_kana %> <%= @customer.first_name_kana %></p>
    <p>郵便番号 <%= @customer.postal_code %></p>
    <p>住所 <%= @customer.address %></p>
    <p>電話番号 <%= @customer.telephone_number %></p>
    <p>メールアドレス <%= @customer.email %></p>
      <div class="input-group">
        <p>会員ステータス   <% if @customer.is_active %>
                           <p class="text-success"> 有効 </p>
                           <% elsif %>
                           <p class="text-meted"> 退会 </p>
                           <% end %> </p>
      </div>
      <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success m-5" %>
</div>